### ISSUE TITLE
I18n problem: doesn't find error messages

### ISSUE THREAD

**Issue by jmuheim** [perfectline/validates_url#33] opened 2015-10-22 08:23 UTC
I'm not presented with the expected error messages. Instead:

![image](https://cloud.githubusercontent.com/assets/1814983/10660331/83ae3cd6-78a6-11e5-828a-ab366ee7525f.png)

Or:

![image](https://cloud.githubusercontent.com/assets/1814983/10660338/8c5e0f82-78a6-11e5-9a04-8e27c263d40a.png)

I then tried this as a workaround:

```
validates :url, url: {allow_blank: true, message: I18n.t('errors.messages.url')}
```

But this results in this:

![image](https://cloud.githubusercontent.com/assets/1814983/10660388/f0555bbc-78a6-11e5-934d-e536155d743e.png)

I have restarted the server, etc.

I'm on Rails 4.2, is this maybe the problem?

**Comment by jmuheim** [comment] 2015-10-22 08:25
Only when manually adding it to my own locale files, it works:

![image](https://cloud.githubusercontent.com/assets/1814983/10660426/3fe9345a-78a7-11e5-8695-5fcbd5b3eb87.png)

**Comment by kritik** [comment] 2015-10-23 07:54
In first screenshot "de" locale is missing but in the second you're typing translation for "en" locale. Can problem be in it?

**Comment by jmuheim** [comment] 2015-10-26 07:54
No, that doesn't seem to be the problem, I have both translated. Should I give you access to the repo so you can investigate in the app in question?

**Comment by kritik** [comment] 2015-10-31 12:08
I think you're doing smth wrong. No one other has claimed there's such problem

**Comment by marcelotto** [comment] 2016-04-14 12:22
I'm having this problem, too. Also using Rails 4.2. Also with locale "de".

**Comment by Arpsara** [comment] 2016-04-21 16:18
Hi, I have the same problem, but with the locale "fr" on Rails 4.2.

By default, it seems to search in:

fr:
  activerecord:
      models:
        my_model_name:
          attributes:
            my_attribute:
              url: "missing translation"
... which is quite long. :)

Following jmuheim steps, adding a I18n.t('errors.messages.url') doesn't work for me neither, I had to add it manually, even with gaga5lala fix.

**Comment by gaga5lala** [comment] 2016-04-22 15:09
Hi @Arpsara, can you help me check this file `lib/validate_url.rb`, you can find it by this command
`gem which validate_url`. Does the file same as which on github?

If not, please help me do one another thing, install the gem from github by put this line in your Gemfile `gem 'validate_url', :git => 'https://github.com/perfectline/validates_url.git'`, and test again.

@kritik I'm not familiar with ruby gem release flow, does this patch need to update to rubygems.org?

**Comment by Arpsara** [comment] 2016-04-25 08:51
@gaga5lala: `gem which validate_url` didn't work, so I made a `gem list` and` bundle show validate url ` to check the file.
At first, the file wasn't the same. When I added the git repo to the gemifle, the file was the same. :)
I think you have to update the gem in rubygem.org. :)

Also... It's weird, but I can't get the error anymore, using both versions of the gem... Maybe just restarting the server manually (even when using guard) does the trick? I can't say.

**Comment by gaga5lala** [comment] 2016-04-25 09:53
@Arpsara Try `spring stop` to terminate app cache by [spring](https://github.com/rails/spring) :)

**Comment by kritik** [comment] 2016-07-05 05:59
Can I close this issue?

**Comment by gaga5lala** [comment] 2016-07-06 22:54
@kritik: Do we need an update for rubygems.org?

**Comment by Arpsara** [comment] 2016-08-01 14:31
I can not reproduce the bug, but I'm not sure if it can be closed.

**Comment by kritik** [comment] 2017-02-23 07:05
@gaga5lala no, It's not a problem with versioning. Anyway closing an issue

**Closed by kritik** 2017-02-23 07:05 UTC

**Comment by jmosouza** [comment] 2017-03-13 15:14
**Changing Gemfile to use GitHub solves it for now:**

```
gem "validate_url", github: "perfectline/validates_url"
```

@kritik RubyGems needs to be updated.

Version 1.0.2 from RubyGems only has `en`, `tr` and `ja`.

Rails console: `I18n.load_path.select { |path| path.include? "validate_url" }`

Output:

```
[
    [0] "/Users/joao/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/validate_url-1.0.2/lib/locale/en.yml",
    [1] "/Users/joao/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/validate_url-1.0.2/lib/locale/tr.yml",
    [2] "/Users/joao/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/validate_url-1.0.2/lib/locale/ja.yml"
]
```

**Comment by kritik** [comment] 2017-03-14 06:49
I would say it's totally different issue

**Comment by jmosouza** [comment] 2017-03-14 11:04
I believe it's really this issue because everyone said their application is an a locale that's neither `en`, `tr` or `ja`. Possibly the translation is missing for them because 1.0.2 (currently the latest) on RubyGems does not contain translations for `de`, `fr` and `pt-BR`.

- jmuheim: `de`
- marcelotto: `de`
- Arpsara: `fr`
- jmosouza: `pt-BR` (I forgot to mention)

[There are translations for these locales on the `master` branch](https://github.com/perfectline/validates_url/tree/master/lib/locale), but not on 1.0.2 at RubyGems.
